= IP filtering policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-ipfiltering/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-ipfiltering/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

|===
|onRequest |onResponse

|X
|

|===

== Description

You can use the `ip-filtering` policy to control access to your API by filtering IP addresses.
You can allow or deny a specific IP address or range of IP addresses with https://tools.ietf.org/html/rfc1519[CIDR^].

Whitelist mode excludes all IP addresses except the addresses included in the whitelist.
Blacklist mode allows all IP addresses except the addresses included in the blacklist.

The blacklist takes precedence, so if an IP address is included in both lists, the policy rejects the request.

You can specify a host to be resolved and checked against the remote IP.

== Configuration
You can configure the policy with the following options:

|===
|Property |Required |Description |Type |Default

|matchAllFromXForwardedFor
|No
|If set to `true`, each IP from the `X-Forwarded-For` header parameter is parsed
|boolean
|`false`

|whitelistIps
|No
|A list of allowed IPs with or without CIDR notation (host is allowed)
|string list
|`empty`

|blacklistIps
|No
|A list of denied IPs with or without CIDR notation (host is allowed)
|string list
|`empty`

|===

== Examples

[source, json]
----
"ip-filtering": {
  "matchAllFromXForwardedFor": true,
  "whitelistIps": [
    "10.0.0.1",
    "10.0.0.2/10",
    "gravitee.io"
  ],
  "blacklistIps": [
    null
  ]
}
----

== Errors

=== HTTP status code

|===
|Code |Message

| ```403```
| Your IP (0.0.0.0) or one of the proxies your request passed through is not allowed to reach this resource

|===
